// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA8seHIfaV-eMKGZlfR8e0W1BRbgpvND8',
    appId: '1:762384632071:web:1dad901de7d17ca3409da2',
    messagingSenderId: '762384632071',
    projectId: 'namma-dash',
    authDomain: 'namma-dash.firebaseapp.com',
    storageBucket: 'namma-dash.appspot.com',
    measurementId: 'G-BCHTL7J0EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUic8istpvFNPdBPyVY9FBiYOWkAWMWc',
    appId: '1:762384632071:android:e9273d49f3fabfee409da2',
    messagingSenderId: '762384632071',
    projectId: 'namma-dash',
    storageBucket: 'namma-dash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzPrwV_gAiX3Qeilzn4SUY7nli4s46ljY',
    appId: '1:762384632071:ios:9e13a1ac8c059780409da2',
    messagingSenderId: '762384632071',
    projectId: 'namma-dash',
    storageBucket: 'namma-dash.appspot.com',
    iosBundleId: 'dev.app2pack.flappydash.flappyDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzPrwV_gAiX3Qeilzn4SUY7nli4s46ljY',
    appId: '1:762384632071:ios:9e13a1ac8c059780409da2',
    messagingSenderId: '762384632071',
    projectId: 'namma-dash',
    storageBucket: 'namma-dash.appspot.com',
    iosBundleId: 'dev.app2pack.flappydash.flappyDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA8seHIfaV-eMKGZlfR8e0W1BRbgpvND8',
    appId: '1:762384632071:web:8451df33b952f76d409da2',
    messagingSenderId: '762384632071',
    projectId: 'namma-dash',
    authDomain: 'namma-dash.firebaseapp.com',
    storageBucket: 'namma-dash.appspot.com',
    measurementId: 'G-82CZ30T2TV',
  );
}
